### ISSUE TITLE
hi, regular expression parse error

### ISSUE THREAD

**Issue by StriveMario** [Siubaak/sval#21]
test code:
interpreter.run('var s =/(^ws:\/\/)/;')

The following error occurs:

SyntaxError: Invalid regular expression: /(^ws:/: Unterminated group (1:8)
    at Parser.pp$4.raise (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:2757:13)
    at RegExpValidationState.raise (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3530:15)
    at Parser.pp$9.regexp_eatCapturingGroup (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3841:11)
    at Parser.pp$9.regexp_eatExtendedAtom (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3853:10)
    at Parser.pp$9.regexp_eatTerm (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3703:57)
    at Parser.pp$9.regexp_alternative (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3684:50)
    at Parser.pp$9.regexp_disjunction (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3668:8)
    at Parser.pp$9.regexp_pattern (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3641:8)
    at Parser.pp$9.validateRegExpPattern (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:3617:8)
    at Parser.pp$8.readRegexp (c:\Users\Administrator\node_modules\acorn\dist\acorn.js:4941:8)

**Comment by Siubaak** [comment]
/(^ws://)/的/需要转义的吧，/(^ws:\/\/)/才对
